# Generated by Django 6.0.2 on 2026-02-23 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Desktop', 'Desktop PC'), ('CPU', 'Processor'), ('GPU', 'Graphics Card'), ('RAM', 'Memory'), ('SSD', 'Storage'), ('Motherboard', 'Motherboard'), ('PSU', 'Power Supply'), ('Cabinet', 'Cabinet')], max_length=100)),
            ],
        ),
    ]
